---
title: "HUDECA — Figure 2: Composition and development of the human olfactory system at PCW7-PCW12"
author: "Mbouamboua Yvon <yvon.mbouamboua@inserm.fr>"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
date: '`r format(Sys.Date())`'
---

## Goal
Final figures

## Setup
```{r setup, include=TRUE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE, comment = "")
dir.main <- "/Users/yvon.mbouamboua/projects/singlecell/000-hudeca-nose"
dir.results <- file.path(dir.main, "output", "010-figures/figure2")
dir.create(dir.results, showWarnings = FALSE, recursive = TRUE)
dir.create(file.path(dir.results, "data"), showWarnings = FALSE)

# Load packages
packages <- c("Seurat", "ggplot2", "dplyr", "grid",
"SingleCellExperiment", "scran", "scater",
"pheatmap", "ComplexHeatmap", "ComplexUpset", "patchwork")
install_and_load <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
  library(pkg, character.only = TRUE)
}
invisible(lapply(packages, install_and_load))

# Load helper functions
utils_dir <- "~/projects/apps/"
r_files <- list.files(utils_dir, pattern = "\\.R$", full.names = TRUE)
invisible(lapply(r_files, source))

# Load custom colors 
custom_colors <-  readRDS(file.path(dir.main, "analysis/custom-colors-nature-safe.rds"))

```


# Load data

```{r}

obj <- readRDS(file.path(dir.main, "output/002-annotation/data/FN_harmony_clean.rds"))

```


# Fig2b

```{r fig.width=5, fig.height=3.5}

sub <- seurat_subset(obj, group.by = "ann2", use.harmony = T, harmony.group = "sample",
                     min.dist = 1, spread = 0.5, idents = c("OHBC", "CycBasal", "MV","SUS","GBC","INP","iOSN"))

p <- cellmap(object = sub, group.by = "ann2", label = F, legend = T, item.size = 3,
              figplot = T, cols = custom_colors$ann2, font.size = 10, n.cells = F, leg.ttl = "", pt.size = 0.5)
p
savefig(fig = p, filename = file.path(dir.results, "fig2b"), width = 5, height = 3.5)


p <- cellmap(object = sub, group.by = "ann2", label = T, legend = F, label.size = 4,label.face = "bold",
              figplot = T, cols = custom_colors$ann2, font.size = 10, pt.size = 0.5)
p
savefig(fig = p, filename = file.path(dir.results, "fig2b-v2"), width = 5, height = 3.5)


```

## Fig2c

```{r fig.width=10, fig.height=3}

res <- pb_prop_plot(input = sub, donor.col = "sample", stage.col = "stage", cell.col  = "ann2", ncol = 7, show.p = F, leg.pos = "none",
  plot.type = "bar", stage.cols = custom_colors$PCW, donor.cols = custom_colors$donor, pt.size = 1.5, facet.by = "cell", font.size = 10, facet.bg = F)

res$plot   # display plot
res$stats  # view LMM/KW p-values
savefig(fig = res$plot, filename = file.path(dir.results, "fig2c"), width = 10, height = 3)

```


# Fig2d

```{r fig.width=3, fig.height=3}

sub <- seurat_subset(obj,  group.by = "ann2", use.harmony = T, harmony.group = "sample",
                     min.dist = 1, spread = 0.5, idents = c("RHBC","OHBC","GBC"))

p <- celldot(sub, features = rev(c("TP63","KRT5","KRT17","CXCL14","SOX2","MEG3","COL17A1","RASSF6","MYBL1","NNAT","HES6","EZH2")), 
             group.by = "ann2", flip = T, font.size = 10, x.angle = 45)
p
savefig(fig = p, filename = file.path(dir.results, "fig2d"), width = 3, height = 3)

```


# Fig2e

```{r fig.width=2, fig.height=4}

sub <- seurat_subset(obj, idents = c("OHBC","RHBC"), group.by = "ann2")

p <- cellvio(sub, group.by = "ann2", features = c("MEG3"), pt.size = 0, 
             font = 10, cols = custom_colors$ann2, show.pval = T, add.stats = T, pairwise = T)
p
savefig(fig = p, filename = file.path(dir.results, "fig2e"), width = 1.5, height = 4)

```


# Session Info

```{r session_info}
utils::capture.output(devtools::session_info())
```


