---
title: "HUDECA — 000 PREPROCESSING"
author: "Mbouamboua Yvon <yvon.mbouamboua@inserm.fr>"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
date: '`r format(Sys.Date())`'
---

## Goal
Quality control and normalization

## Setup
```{r setup, include=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, comment = "")
dir.main <- "/Users/yvon.mbouamboua/projects/singlecell/000-hudeca-nose"
dir.data <- file.path(dir.main, "data/processed")
dir.results <- file.path(dir.main, "output", "000-preprocessing")
dir.create(dir.results, showWarnings = FALSE, recursive = TRUE)
dir.create(file.path(dir.results, "plots"), showWarnings = FALSE)

# Load packages
packages <- c("Seurat", "ggplot2", "dplyr", "grid",
"SingleCellExperiment", "scran", "scater",
"pheatmap", "ComplexHeatmap", "ComplexUpset", "patchwork")
install_and_load <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
  library(pkg, character.only = TRUE)
}
invisible(lapply(packages, install_and_load))

# Load helper functions
dir.utils <- "~/projects/apps/"
files <- list.files(dir.utils, pattern = "\\.R$", full.names = TRUE)
invisible(lapply(files, source))
```


# Create seurat objects


```{r}

samples <- c("FN_S1256", "FN_S3478")

objs <- load_seurat(
  sample.dirs = samples,
  parent.dir = file.path(dir.main, "data/processed"),
  use.filtered = TRUE,
  save.dir = file.path(dir.results, "data"),
  merge = FALSE
)

```

# Add demuxafy

```{r}

# Minimal helper function
process_demux_run <- function(obj, tsv_path, donor_map_path, bulk_fix_fun, barcode_col = "Barcode") {
  df <- read.delim(tsv_path) %>%
    bulk_fix_fun()
  donor_mapping_tsv <- read.delim(donor_map_path)
  obj <- add_bulk_donor_mapping_to_seurat(obj, df, donor_mapping_tsv, barcode_col = barcode_col)
  Idents(obj) <- "BulkSample"
  obj <- get_subset(obj, idents = c("doublet", "unassigned"), invert = TRUE)
  return(obj)
}


fix_bulk <- function() {
  function(df) {
    df %>%
      mutate(BulkSample = case_when((is.na(BulkSample) | BulkSample == "") &
            MappingStatus == "doublet" ~ "doublet", 
            is.na(BulkSample) | BulkSample == "" ~ "unassigned",TRUE ~ BulkSample))
  }
}

FN_S1256 <- process_demux_run(
  obj = objs$FN_S1256,
  tsv_path = file.path(dir.main, "python/notebook/FN_S1256_bulk_mapping/combined_results_with_bulk_mapping.tsv"),
  donor_map_path = file.path(dir.main, "python/notebook/FN_S1256_bulk_mapping/donor_to_bulk_mapping.tsv"),
  bulk_fix_fun = fix_bulk()
)

FN_S3478 <- process_demux_run(
  obj = objs$FN_S3478,
  tsv_path = file.path(dir.main, "python/notebook/FN_S3478_bulk_mapping/combined_results_with_bulk_mapping.tsv"),
  donor_map_path = file.path(dir.main, "python/notebook/FN_S1256_bulk_mapping/donor_to_bulk_mapping.tsv"),
  bulk_fix_fun = fix_bulk()
)

raw_merged <- get_merge(obj.list = list(FN_S1256, FN_S3478))

```

# Quality control

```{r}

seurat_list <- split_seurat_objects(raw_merged, split.by = "BulkSample")
invisible(gc())

obj <- run_qc(x = seurat_list, min_feat = 500, min_umi = 500, mad_n = 5, max_mito = 5,
                      species = "human", sample_col = "BulkSample",
                      merge_output = T, outdir = file.path(dir.results, "data"))

rm(seurat_list, merged)
invisible(gc())

```


# Save data

```{r}

saveRDS(raw_merged, file.path(dir.results, "data/raw_merged.rds"))
saveRDS(obj, file.path(dir.results, "data/filt_merged.rds"))

```


# Session Info

```{r session_info}
utils::capture.output(devtools::session_info())
```

