---
title: "HUDECA — Figure 1: Single-nucleus RNA sequencing of the developing human olfactory sensory epithelium from post-conceptional weeks (PCW) 7 to 12"
author: "Mbouamboua Yvon <yvon.mbouamboua@inserm.fr>"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
date: '`r format(Sys.Date())`'
---

## Goal
Final figures

## Setup
```{r setup, include=TRUE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE, comment = "")
dir.main <- "/Users/yvon.mbouamboua/projects/singlecell/000-hudeca-nose"
dir.results <- file.path(dir.main, "output", "010-figures/figure1")
dir.create(dir.results, showWarnings = FALSE, recursive = TRUE)
dir.create(file.path(dir.results, "data"), showWarnings = FALSE)
dir.create(file.path(dir.results, "plots"), showWarnings = FALSE)

# Load packages
packages <- c("Seurat", "ggplot2", "dplyr", "grid",
"SingleCellExperiment", "scran", "scater",
"pheatmap", "ComplexHeatmap", "ComplexUpset", "patchwork")
install_and_load <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
  library(pkg, character.only = TRUE)
}
invisible(lapply(packages, install_and_load))

# Load helper functions
utils_dir <- "~/projects/apps/"
r_files <- list.files(utils_dir, pattern = "\\.R$", full.names = TRUE)
invisible(lapply(r_files, source))

# Load custom colors 
custom_colors <-  readRDS(file.path(dir.main, "analysis/custom-colors-nature-safe.rds"))

```


# Load data


```{r}

obj <- readRDS(file.path(dir.main, "output/002-annotation/data/FN_harmony_clean.rds"))

levels(obj$ann2)

```


# Fig1b

```{r fig.width=12, fig.height=5, warning=F, message=F}

p <- cellmap(object = obj, group.by = "sample", split.by = "sample", label= F, figplot = F, plot.ttl = "",
              legend = F, cols = custom_colors$sample, font.size = 10, pt.size = 0, ncol = 4, no.axes = T) 
p
savefig(fig = p, filename = file.path(dir.results, "fig1b.pdf"),  width = 7, height = 4)

```




# Fig1c

```{r}

p <- cellmap(object = obj, group.by = "sample", label = F, legend = T, item.size = 3, font.size = 10,
              figplot = T, label.size = 3, cols = custom_colors$sample,  leg.ttl = "Samples")
p
savefig(fig = p, filename = file.path(dir.results, "fig1c"), width = 6.5, height = 5)

```

# Fig1d

```{r }

p <- cellmap(object = obj, group.by = c("ann2"), label = T, legend = T, font.size = 10,
              figplot = T, label.size = 3, cols = custom_colors$ann2, label.face = "bold",
             leg.ttl = "Cell types",leg.ncol = 2)
p
savefig(fig = p, filename = file.path(dir.results, "fig1d"),  width = 6.5, height = 4)

```

# Fig1e

```{r}

p <- residual_plot(data=obj, plot.type = "bar",cell.col = "ann2", 
              group.col = "sex", jitter.size = 0.5, 
              stage.col = "stage", group.colors = custom_colors$sex, 
              stage.colors = custom_colors$PCW, font.size = 10,
              leg.pos = c(0.05, 0.8), alpha = 0.5, xlab = T)
p
savefig(fig = p, filename = file.path(dir.results, "fig1e"),  width = 7, height = 4)

p <- residual_plot(data=obj, plot.type = "box",cell.col = "ann2", 
              group.col = "sex", jitter.size = 0.5, 
              stage.col = "stage", group.colors = custom_colors$sex, 
              stage.colors = custom_colors$PCW, font.size = 10,
              leg.pos = c(0.05, 0.8), alpha = 0.5, xlab = F)
p
savefig(fig = p, filename = file.path(dir.results, "fig1e_no_xlab"),  width = 7, height = 4)

```




# Fig1f

```{r fig.width=8, fig.height=5}

#colnames(obj@meta.data)[colnames(obj@meta.data) == "mito"] <- "percent_mito"

p <- cellvio(obj, features = c("nFeature_RNA", "nCount_RNA", "percent_mito"), group.by = "ann2",
  cols = custom_colors$ann2, ttl.pos = "left", font.size = 10,  stack = T, pt.size = 0)

p
savefig(fig = p, filename = file.path(dir.results, "fig1f"), width = 7, height = 5)

```




# Fig1g

```{r fig.width=4, fig.height=5}

sub <- get_subset(obj, idents = c("Epithelium"), group.by = "ann0")
sub <- genefilter(sub)
markers <- cellmarker(sub,  group.by = "ann2", only.pos = T, logfc.threshold = 0.25, min.pct = 0.25, test.use = "MAST")
write.table(markers, file.path(dir.results, "data/ann2_epith.tsv"), sep = "\t", row.names = F, quote = F)
markers <- read.delim(file.path(dir.results, "data/ann2_epith.tsv"))
top <- markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_log2FC)
p <- celldot(sub, features = rev(c(top$gene)), group.by = "ann2", 
              plot.title = "Epithelium", flip = T,  x.angle = 45, font.size = 10) 
p
savefig(fig = p, filename = file.path(dir.results, "fig1g1"), width = 4, height = 5)

```




```{r fig.width=4, fig.height=5}

sub <- get_subset(obj, idents = c("Neuronal","NCC-Glia"), group.by = "ann0")
sub <- filter_genes(sub)
markers <- cellmarker(sub,  group.by = "ann2", only.pos = T, logfc.threshold = 0.25, min.pct = 0.25, test.use = "MAST")
write.table(markers, file.path(dir.results, "data/ann2_ncc_glia.tsv"), sep = "\t", row.names = F, quote = F)
markers <- read.delim(file.path(dir.results, "data/ann2_ncc_glia.tsv"))
top <- markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_log2FC)
p <- celldot(sub, features = rev(c(top$gene)), group.by = "ann2", 
              plot.title = "Neural - Glial", flip = T,  x.angle = 45, font.size = 10) 
p
savefig(fig = p, filename = file.path(dir.results, "fig1g2"), width = 4, height = 5)

```


```{r fig.width=3.5, fig.height=4.5}

sub <- get_subset(obj, idents = c("Mesenchyme"), group.by = "ann0")
sub <- filter_genes(sub)
markers <- cellmarker(sub,  group.by = "ann2", only.pos = T, logfc.threshold = 0.25, min.pct = 0.25, test.use = "MAST")
write.table(markers, file.path(dir.results, "data/ann2_mes.tsv"), sep = "\t", row.names = F, quote = F)
markers <- read.delim(file.path(dir.results, "data/ann2_mes.tsv"))
top <- markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_log2FC)
p <- celldot(sub, features = rev(c(top$gene)), group.by = "ann2", 
              plot.title = "Mesenchyme", flip = T,  x.angle = 45, font.size = 10) 
p
savefig(fig = p, filename = file.path(dir.results, "fig1g3"), width = 3.5, height = 4.5)

```


```{r fig.width=3.5, fig.height=4.5}

sub <- get_subset(obj, idents = c("Vascular","Muscle","Immune"), group.by = "ann0")
sub <- filter_genes(sub)
markers <- cellmarker(sub,  group.by = "ann2", only.pos = T, logfc.threshold = 0.25, min.pct = 0.25, test.use = "MAST")
write.table(markers, file.path(dir.results, "data/ann2_vasc_mus_imm.tsv"), sep = "\t", row.names = F, quote = F)
markers <- read.delim(file.path(dir.results, "data/ann2_vasc_mus_imm.tsv"))
top <- markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_log2FC)
p <- celldot(sub, features = rev(c(top$gene)), group.by = "ann2", 
              plot.title = "Vascular - Muscle - Immune", flip = T,  x.angle = 45, font.size = 10) 
p
savefig(fig = p, filename = file.path(dir.results, "fig1g4"), width = 3.5, height = 4.5)

```


```{r fig.width=8, fig.height=3.5}

obj <- filter_genes(obj, normalize = T, scale.data = T)
markers <- cellmarker(obj,  group.by = "ann0", only.pos = T, logfc.threshold = 0.25, min.pct = 0.25, test.use = "MAST")
write.table(markers, file.path(dir.results, "data/ann0_markers.tsv"), sep = "\t", row.names = F, quote = F)
markers <- read.delim(file.path(dir.results, "data/ann0_markers.tsv"))
top <- markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC)
p <- celldot(obj, features = top$gene, group.by = "ann0", 
              plot.title = "Annotation level0", flip = F,  x.angle = 90, font.size = 10) 
p
savefig(fig = p, filename = file.path(dir.results, "fig_ann0_markers"), width = 8, height = 3.5)

```


```{r fig.width=10, fig.height=3.5}

obj <- filter_genes(obj, normalize = T, scale.data = T)
markers <- cellmarker(obj,  group.by = "ann1", only.pos = T, logfc.threshold = 0.25, min.pct = 0.25, test.use = "MAST")
write.table(markers, file.path(dir.results, "data/ann1_markers.tsv"), sep = "\t", row.names = F, quote = F)
markers <- read.delim(file.path(dir.results, "data/ann1_markers.tsv"))
top <- markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC)
p <- celldot(obj, features = top$gene, group.by = "ann1", 
              plot.title = "Annotation level1", flip = F,  x.angle = 90, font.size = 10) 
p
savefig(fig = p, filename = file.path(dir.results, "fig_ann1_markers"), width = 10, height = 3.5)

```


```{r fig.width=15, fig.height=5}

obj <- filter_genes(obj, normalize = T, scale.data = T)
markers <- cellmarker(obj,  group.by = "ann2", only.pos = T, logfc.threshold = 0.25, min.pct = 0.25, test.use = "MAST")
write.table(markers, file.path(dir.results, "data/ann2_markers.tsv"), sep = "\t", row.names = F, quote = F)
markers <- read.delim(file.path(dir.results, "data/ann2_markers.tsv"))
top <- markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_log2FC)
p <- celldot(obj, features = top$gene, group.by = "ann2", 
              plot.title = "Annotation level2", flip = F,  x.angle = 90, font.size = 10) 
p
savefig(fig = p, filename = file.path(dir.results, "fig_ann2_markers"), width = 15, height = 5)


```


```{r fig.width=6.5, fig.height=10}

canonical_markers <- c(
  # Basal / progenitors
  "TP63", "KRT5", "KRT19",        # RHBC
  "COL17A1","TP63", "KRT5",              # OHBC
  "TOP2A", "MKI67",               # CycBasal
  
  # Olfactory neuronal lineage
  "HES6", "NNAT", "MYBL1",        # GBC
  "NEUROD1", "NEUROG1", "TEX15",           # INP
  "GNAL", "ADCY3", "GNG13",       # iOSN
  
  # Epithelial differentiation
  "CDC20B", "CCNO",               # Deut
  "FOXJ1","RSPH1", "DTHD1",             # MCC
  "CFTR", "SERPINB7",             # MV
  "IQCJ-SCHIP1", "SLCO1A2",       # SUS
  
  # Neural populations
  "PAX6", "SOX2",                 # NP
  "NEUROD6", "SLC24A2",           # GLUT
  "GAD1", "GAD2",                 # GABA
  "GNRH1", "PTPRN1",              # GnRH
  "NOS1", "CHRM2",                # NOS1
  
  # Glial / support cells
  "CDH19", "DCC",                 # NCC
  "TOP2A", "BUB1",                # SCP
  "COL19A1", "OLFML2A",           # SC
  "SLC38A11", "TMOD1",             # OEC
  "MITF", "HEY2",                 # Mel
  
  # Mesenchymal / stromal
  "SOX2", "GSTP1",                # MSC
  "KIF18B",                       # Mes0
  "ITGA8", "PAX9",                # Mes1
  "CREB5", "NRG1",                # Mes2
  "COL13A1", "ANO5",              # Osteo
  "ACAN", "COL9A2",               # Cartl
  "PDGFRB", "ABCC9",              # Peri
  
  # Vascular / immune / muscle
  "VWF", "FLT1",                  # EC
  "PROX1", "STAB2",               # Lymph
  "PAX7", "PDE1C",                # Sat
  "MYPN", "ASB5",                 # SM
  "CSF1R", "CD163"               # MG
)

p <- celldot(obj, features = canonical_markers, group.by = "ann2", 
              plot.title = "Canonical markers for cell type annotations", flip = T,  x.angle = 90, font.size = 10) 
p
savefig(fig = p, filename = file.path(dir.results, "fig_ann2_canonical_markers"), width = 6.5, height = 10)

```


# Session Info

```{r session_info}
utils::capture.output(devtools::session_info())
```


