---
title: "HUDECA — Figure 6: Analysis of the expression of the olfactory receptors (ORs) in the fetal human olfactory system"
author: "Mbouamboua Yvon <yvon.mbouamboua@inserm.fr>"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
date: '`r format(Sys.Date())`'
---

## Goal
Final figures

## Setup
```{r setup, include=TRUE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE, comment = "")
dir.main <- "/Users/yvon.mbouamboua/projects/singlecell/000-hudeca-nose"
dir.results <- file.path(dir.main, "output", "010-figures/figure6")
dir.create(dir.results, showWarnings = FALSE, recursive = TRUE)
dir.create(file.path(dir.results, "data"), showWarnings = FALSE)

# Load packages
packages <- c("Seurat", "ggplot2", "dplyr", "grid", "decoupleR",
"SingleCellExperiment", "scran", "scater", "slingshot",
"pheatmap", "ComplexHeatmap", "ComplexUpset", "patchwork")
install_and_load <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
  library(pkg, character.only = TRUE)
}
invisible(lapply(packages, install_and_load))

# Load helper functions
utils_dir <- "~/projects/apps/"
r_files <- list.files(utils_dir, pattern = "\\.R$", full.names = TRUE)
invisible(lapply(r_files, source))

# Load custom colors 
custom_colors <-  readRDS(file.path(dir.main, "analysis/custom-colors-nature-safe.rds"))

```


# Load data

```{r}

obj <- readRDS(file.path(dir.main, "output/002-annotation/data/FN_harmony_clean.rds"))

```


# Fig6a

```{r}

plot_gene_set_expression <- function(object,
                                     features,
                                     threshold = 0.5,
                                     set.log = TRUE,
                                     x.angle = 0,
                                     x.lab = FALSE,
                                     theme = "classic",
                                     font.size = 8,
                                     leg.pos = c(0.25, 0.9),
                                     ...) {
  
  # Subset the Seurat object for the selected genes
  filt <- subset(object, features = features)
  filt <- filt[rowSums(filt[["RNA"]]@layers$counts > 0) > 0, ]
  
  # Extract normalized expression data for these genes
  expr_data <- FetchData(filt, vars = rownames(filt))
  
  # Calculate the mean expression for each receptor across all cells
  mean_expression <- colMeans(expr_data)
  
  # Create a data frame for plotting
  expr_df <- data.frame(Receptor = names(mean_expression),
                        Expression = mean_expression)
  
  # Order by expression levels
  expr_df <- expr_df[order(expr_df$Expression), ]
  
  # Calculate the number of olfactory receptors (excluding VN1R1 and VN1R2)
  num_olfactory_receptors <- sum(!expr_df$Receptor %in% c("VN1R1", "VN1R2"))
  
  # Create a label for the olfactory receptors that includes the count
  olfactory_label <- paste0("Olfactory receptors (", num_olfactory_receptors, ")")
  
  # Modify the Receptor_Group to include specific labels
  expr_df$Receptor_Group <- ifelse(expr_df$Receptor %in% c("VN1R1", "VN1R2"),
                                   expr_df$Receptor, olfactory_label)
  
  # Set colors for the plot
  fill_colors <- c("VN1R1" = "red", "VN1R2" = "orange", "Olfactory receptors (0)" = "#20679B")
  fill_colors[olfactory_label] <- "#20679B"
  
  # Count the number of cells expressing each receptor
  expressing_cells <- expr_data > threshold
  cell_counts <- colSums(expressing_cells)
  expr_df$Cell_Count <- cell_counts[match(expr_df$Receptor, names(cell_counts))]
  
  # Optionally calculate -log10(expression) for better visualization
  if (set.log) {
    expr_df$Log_Expression <- -log10(expr_df$Expression)
    y_var <- "Log_Expression"
    y_label <- "-Log10(Normalized Expression)"
  } else {
    expr_df$Log_Expression <- expr_df$Expression
    y_var <- "Expression"
    y_label <- "Normalized Expression"
  }
  
  # Plot the expression levels
  p <- ggplot(expr_df, aes(x = reorder(Receptor, !!sym(y_var)), y = !!sym(y_var), fill = Receptor_Group)) +
    geom_bar(stat = "identity") +
    scale_fill_manual(values = fill_colors, name = "Receptor types") +
    labs(x = "Receptors", y = y_label) +
    plot_theme(theme = theme,
               leg.pos = leg.pos,
               font.size = font.size,
               x.angle = x.angle,
               xlab = x.lab,
               ...) 
  
  return(p)
}

```


```{r fig.width=6, fig.height=4}

sub <- seurat_subset(obj,  group.by = "ann2",  use.harmony = T,  harmony.group = "sample", min.dist = 1, spread = 0.5,  idents = c("INP","iOSN"))
ORs <- readxl::read_excel(file.path(dir.main, "data/processed/ORs/401_ORs.xlsx"))
genes <- intersect(ORs$Gene_name, rownames(sub[["RNA"]]@layers$counts))
genes <- c(genes, "VN1R1", "VN1R2")
length(genes)

p <- plot_gene_set_expression(object = sub,  features = genes, threshold = 0, set.log = T,
                              leg.pos = c(0.30, 0.9), theme = "classic", font.size = 10)
p
savefig(fig = p, filename = file.path(dir.results, "fig6a"), width = 4, height = 3)
write.table(p$data, file = file.path(dir.results, "data/table_fig6a.tsv"), sep = "\t", row.names = F, quote = F)

```

## Fig6b

```{r fig.width=3, fig.height=2.5}

cell_levels <- c("OHBC", "CycBasal", "MV", "SUS", "GBC", "INP", "iOSN")
sample_levels <- c("PCW7-8", "PCW10","PCW12")

Idents(obj) <- "ann2"
sub <- seurat_subset(obj,  group.by = "ann2",  use.harmony = T,  
                     harmony.group = "sample", min.dist = 1, spread = 0.5,
                     idents = c("OHBC", "CycBasal", "MV", "SUS", "GBC", "INP", "iOSN"))
cellmap(sub, group.by = "ann2")

ORs <- readxl::read_excel(file.path(dir.main, "data/processed/ORs/401_ORs.xlsx"))
genes <- intersect(ORs$Gene_name, rownames(sub[["RNA"]]@layers$counts))

p <- genesum(
  object = sub,
  gene.list = genes,
  group.var = "ann2",
  fill.var = "group",font.size = 10,
  leg.pos = c(0.25, 0.9),
  fill.colors = custom_colors$group, return.data = T
)

p
savefig(fig = p$plot, filename = file.path(dir.results, "fig6b"), width = 3, height = 2)
write.table(p$data, file = file.path(dir.results, "data/table_fig6b.tsv"), sep = "\t", row.names = F, quote = F)


```



## Fig6c


```{r fig.width=6.5, fig.height=5}

sub <- seurat_subset(obj,  group.by = "ann2",  use.harmony = T,  
                     harmony.group = "sample", min.dist = 1, spread = 0.5,
                     idents = c("INP", "iOSN"))

cellmap(sub, group.by = "ann2")

res <- gsetplot(
  obj = sub,pairwise.groups = list("INP","iOSN"),
  group.by = "ann2", 
  stage = "stage",
  geneset = ORs$Gene_name,
  label.size = 2,
  show.sig = T,
  pval = F,
  x.lab = "Olfactory recptors",
  sig.size = 6, 
  lab.size = 10,
  leg.size = 10,
  ann.counts = F,
  leg.ttl.size = 10,
  leg.pos = c(0.25, 0.9),
  facet.label.size = 14,theme = "classic",font.size = 10,
  fill.cols = c("INP" = "#4463D9", "iOSN" = "#C63F70")
)


res$plot
savefig(fig = res$plot, filename = file.path(dir.results, "fig6c"), width = 4, height = 3)
write.table(res$plot@data, file = file.path(dir.results, "data/table_fig6c.tsv"), sep = "\t", row.names = F, quote = F)



```


```{r fig.width=8, fig.height=4}

sub <- seurat_subset(obj,  group.by = "ann2",  use.harmony = T,  harmony.group = "sample",
                     min.dist = 1, spread = 0.5,  idents = c("INP","iOSN"))

sub@meta.data$rev_pwc <- as.character(sub$PCW, levels = c("PCW12","PCW10","PCW8","PCW7"))

res <- gsetplot(
  obj = sub,
  pval = F,show.sig = F,
  geneset = ORs$Gene_name,
  group.by  = "ann2",
  stage = "stage",
  mode = "faceted",facet.bg = FALSE,
  x.lab = "Olfactory receptors",
  module.score = TRUE,
  module.name = "ORscore", theme = "classic",facet.ncol = 4,
  pb.logical = FALSE, panel.fill = "white",
  ann.counts = F, leg.pos = c(0.90, 0.95),
  fill.cols = c("INP" = "#4463D9", "iOSN" = "#C63F70")
)

res$plot
savefig(fig = res$plot, filename = file.path(dir.results, "fig6c_supp"), width = 8, height = 4)
write.table(res$plot@data, file = file.path(dir.results, "data/table_supp_fig6c.tsv"), sep = "\t", row.names = F, quote = F)

```




## Fig6d

```{r fig.width=5, fig.height=4}

sub <- seurat_subset(obj,  group.by = "ann2",  use.harmony = T,  harmony.group = "sample", min.dist = 1, spread = 0.5, idents = c("iOSN"))

OR_family <- readxl::read_excel(file.path(dir.main, "data/processed/ORs/OR_family.xlsx"))

genes <- intersect(OR_family$gene_name, rownames(sub[["RNA"]]@layers$counts))
filt <- subset(sub, features = genes)
expression_matrix <- as.matrix(filt[["RNA"]]@layers$counts)
total_counts <- rowSums(expression_matrix)
selected_genes <- names(total_counts[total_counts > 0])
filt <- subset(filt, features = selected_genes)
OR_family <- subset(OR_family, gene_name %in% rownames(filt))

df <- OR_family %>% 
  dplyr::group_by(family, class) %>% 
  dplyr::summarise(count = n())

df$family <- factor(df$family)
df$class <- factor(df$class)

p <- ggplot(df, aes(x = family, y = count, fill = class)) +
  geom_col(stat = "identity", position=position_dodge(), color = "black", linewidth = 0.2) +
  labs(x = "OR families", y = "number of ORs", title = "") +
  guides(fill=guide_legend(title="Class")) +
  scale_fill_manual(values = c("#BCB82C","#20679B")) +
  plot_theme(theme = "classic", 
               leg.pos = c(0.8, 0.8), 
               font.size = 10, x_angle = 0) +
  theme(legend.key.height = unit(0.4, 'cm'),
    legend.key.width = unit(0.4, 'cm'),
    legend.background = element_blank()) 

print(p)
savefig(fig = p, filename = file.path(dir.results, "fig6d"), width = 5, height = 3)

#OR_family <- OR_family[,c("gene_name","family","class")]
write.table(p@data, file.path(dir.results, "data/table_fig6d.tsv"), sep = "\t", row.names = F, quote = F)

```


# Fig6e

```{r fig.width=8, fig.height=3}

# Compute total OR expression per cell
ORs <- readxl::read_excel(file.path(dir.main, "data/ORs/401_ORs.xlsx"))
OR_genes <- ORs$Gene_name
obj$OR_total_log <- Matrix::colSums(obj[OR_genes, , drop = FALSE])
obj$OR_total_log <- log1p(obj$OR_total_log)   # log-transformed

p <- cellvio(obj, group.by = "ann2", features = "OR_total_log", pt.size = 0, 
             cols = custom_colors$ann2, rm.subttl = T)
p
savefig(fig = p, filename = file.path(dir.results, "fig6e"), width = 7, height = 3)

```


# Fig6h

```{r}

sub <- seurat_subset(obj,  group.by = "ann2",  use.harmony = T,  harmony.group = "sample", 
                     min.dist = 1, spread = 0.5, idents = c("OHBC", "CycBasal", "MV", "SUS", "GBC", "INP", "iOSN"))

ORs <- readxl::read_excel(file.path(dir.main, "data/processed/ORs/401_ORs.xlsx"))
genes <- intersect(ORs$Gene_name, rownames(sub[["RNA"]]@layers$counts))

res <- dominance_score(
  obj = sub,
  geneset = genes,
  group.by = "ann2",
  add.meta = c("sample", "stage", "sex"),
  idents = c("INP", "iOSN"),
  bins = c(-Inf, 0.5, 1, 1.5, 2, Inf)
)

write.table(res$df, file.path(dir.results, "data/table_dominance_score.tsv"), sep = "\t", row.names = F, quote = F)

# Dominance bins
p <- plot_dominance_score(res$df, mode = "bins", ident.col = "ident", colors = colors, font.size = 10)
p
savefig(fig = p, filename = file.path(dir.results, "fig6h"), width = 2.2, height = 3)
write.table(p@data, file.path(dir.results, "data/table_fig6h.tsv"), sep = "\t", row.names = F, quote = F)

```

# Fig6i

```{r}

# High-dominance cells per stage
p <- plot_dominance_score(res$df, mode = "high_cells", ident.col = "ident", stage.col = "stage", colors = colors, leg.dir = "vertical", leg.pos = c(0.2, 0.85))
p
savefig(fig = p, filename = file.path(dir.results, "fig6i"), width = 2.2, height = 3)
write.table(p@data, file.path(dir.results, "data/table_fig6i.tsv"), sep = "\t", row.names = F, quote = F)
```

# Fig6j
```{r}

p <- plot_dominance_score(res$df, mode = "top_genes", top.n = 20)
p
savefig(fig = p, filename = file.path(dir.results, "fig6j"), width = 3, height = 3)
write.table(p@data, file.path(dir.results, "data/table_fig6j.tsv"), sep = "\t", row.names = F, quote = F)


```

```{r fig.width=6, fig.height=7}
# Top dominant genes faceted by stage
p <- plot_dominance_score(res$df, mode = "top_genes", stage.col = "stage", ncol = 4, top.n = 20, font.size = 10)
p
savefig(fig = p, filename = file.path(dir.results, "supp_fig6j"), width = 6, height = 7)
write.table(p@data, file.path(dir.results, "data/table_supp_fig6j.tsv"), sep = "\t", row.names = F, quote = F)

```


# Session Info

```{r session_info}
utils::capture.output(devtools::session_info())
```




