---
title: "HUDECA — Extended Data Figure 2: Quality control of human olfactory epithelium snRNA-seq data"
author: "Mbouamboua Yvon <yvon.mbouamboua@inserm.fr>"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
date: '`r format(Sys.Date())`'
---

## Goal
Final figures

## Setup
```{r setup, include=TRUE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE, comment = "")
dir.main <- "/Users/yvon.mbouamboua/projects/singlecell/000-hudeca-nose"
dir.results <- file.path(dir.main, "output", "010-figures/extended-figure2")
dir.create(dir.results, showWarnings = FALSE, recursive = TRUE)
dir.create(file.path(dir.results, "data"), showWarnings = FALSE)

# Load packages
packages <- c("Seurat", "ggplot2", "dplyr", "grid", "decoupleR",
"SingleCellExperiment", "scran", "scater", "slingshot",
"pheatmap", "ComplexHeatmap", "ComplexUpset", "patchwork")
install_and_load <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
  library(pkg, character.only = TRUE)
}
invisible(lapply(packages, install_and_load))

# Load helper functions
utils_dir <- "~/projects/apps/"
r_files <- list.files(utils_dir, pattern = "\\.R$", full.names = TRUE)
invisible(lapply(r_files, source))

# Load custom colors 
custom_colors <-  readRDS(file.path(dir.main, "analysis/custom-colors-nature-safe.rds"))

```


# Load data

```{r}

FN_S1256 <- readRDS("~/projects/singlecell/000-hudeca-nose/output/000-preprocessing/data/FN_S1256.rds")
FN_S3478 <- readRDS("~/projects/singlecell/000-hudeca-nose/output/000-preprocessing/data/FN_S3478.rds")
raw <- readRDS(file.path(dir.main, "output/000-preprocessing/data/raw_merged.rds"))
integrated <- readRDS(file.path(dir.main, "output/002-annotation/data/FN_harmony.rds"))
obj <- readRDS(file.path(dir.main, "output/002-annotation/data/FN_harmony_clean.rds"))

```


# FigS2a

```{r}

prep <- function(df, run, fix = NULL) {
  df %>%
    mutate(
      BulkSample = if (!is.null(fix)) fix(.) else BulkSample,
      BulkSample = case_when(
        MappingStatus == "doublet"  & (is.na(BulkSample) | BulkSample == "") ~ "doublet",
        MappingStatus == "singlet" & (is.na(BulkSample) | BulkSample == "") ~ "unassigned",
        TRUE ~ BulkSample
      ),
      Run = run
    )
}

# read + clean
d1 <- prep(
  read.delim(file.path(dir.main,
    "python/notebook/FN_S1256_bulk_mapping/combined_results_with_bulk_mapping.tsv")),
  run = "FN_S1256"
)

d2 <- prep(
  read.delim(file.path(dir.main,
    "python/notebook/FN_S3478_bulk_mapping/combined_results_with_bulk_mapping.tsv")),
  run = "FN_S3478"
)

df <- bind_rows(d1, d2)

# summarise 
sum_df <- df %>%
  mutate(
    Status = case_when(
      MappingStatus == "doublet" ~ "Doublet",
      MappingStatus == "singlet" & BulkSample == "unassigned" ~ "Unassigned",
      TRUE ~ "Singlet"
    ),
    Samp = ifelse(Status == "Singlet",
                  BulkSample,
                  paste0(Status, "_", Run))
  ) %>%
  dplyr::count(Samp, Status, name = "n")

# factor order
lvl <- c(
  "S1-PCW7","S2-PCW8","S3-PCW10","S5-PCW10",
  "S4-PCW10.5","S6-PCW12","S7-PCW12","S8-PCW12",
  "Doublet_FN_S1256","Unassigned_FN_S1256",
  "Doublet_FN_S3478","Unassigned_FN_S3478"
)

sum_df$Samp <- factor(sum_df$Samp, levels = lvl)

# plot
p_demux <- ggplot(sum_df, aes(Samp, n, fill = Status)) +
  geom_col(width = 0.65, color = "black", linewidth = 0.2) +
  coord_flip() +
  scale_fill_manual(values = c(
    Singlet = "#8CB9E6",
    Doublet = "black",
    Unassigned = "gray60"
  )) +
  labs(x = NULL, y = "Number of barcodes", fill = "Demultiplexing status") +
  plot_theme(theme = "classic",
             font.size = 10,
             leg.pos = "bottom",
             leg.dir = "horizontal")
p_demux
#  export
savefig(fig = p_demux, filename = file.path(dir.results, "figS2a"), width = 5, height = 4)
write.table(sum_df,
            file.path(dir.results, "data/table_figS2a.tsv"),
            sep = "\t", row.names = FALSE, quote = FALSE)

```


# FigS2b

```{r}

# Minimal helper function
process_demux_run <- function(obj, tsv_path, donor_map_path, bulk_fix_fun, barcode_col = "Barcode") {
  df <- read.delim(tsv_path) %>%
    bulk_fix_fun()
  donor_mapping_tsv <- read.delim(donor_map_path)
  obj <- add_bulk_donor_mapping_to_seurat(obj, df, donor_mapping_tsv, barcode_col = barcode_col)
  Idents(obj) <- "BulkSample"
  obj <- get_subset(obj, idents = c("doublet", "unassigned"), invert = TRUE)
  return(obj)
}

# Run specific mutation rules
# FN_S1256
fix_bulk_1256 <- function() {
  function(df) 
    {df %>%
      mutate(BulkSample = case_when((is.na(BulkSample) | BulkSample == "") &
            MajoritySinglet_DropletType == "singlet" &
            MajoritySinglet_Individual_Assignment == "donor3" ~ "S5-PCW10",TRUE ~ BulkSample),
        BulkSample = case_when(MappingStatus == "doublet"  & BulkSample == "" ~ "doublet",
          MappingStatus == "singlet" & BulkSample == "" ~ "unassigned",TRUE ~ BulkSample))
  }
}

# FN_S3478
fix_bulk_3478 <- function() {
  function(df) {
    df %>%
      mutate(BulkSample = case_when((is.na(BulkSample) | BulkSample == "") &
            MappingStatus == "doublet" ~ "doublet", 
            is.na(BulkSample) | BulkSample == "" ~ "unassigned",TRUE ~ BulkSample))
  }
}

FN_S1256 <- process_demux_run(
  obj = FN_S1256,
  tsv_path = file.path(dir.main, "python/notebook/FN_S1256_bulk_mapping/combined_results_with_bulk_mapping.tsv"),
  donor_map_path = file.path(dir.main, "python/notebook/FN_S1256_bulk_mapping/donor_to_bulk_mapping.tsv"),
  bulk_fix_fun = fix_bulk_1256()
)

FN_S3478 <- process_demux_run(
  obj = FN_S3478,
  tsv_path = file.path(dir.main, "python/notebook/FN_S3478_bulk_mapping/combined_results_with_bulk_mapping.tsv"),
  donor_map_path = file.path(dir.main, "python/notebook/FN_S1256_bulk_mapping/donor_to_bulk_mapping.tsv"),
  bulk_fix_fun = fix_bulk_3478()
)

raw <- get_merge(obj.list = list(FN_S1256, FN_S3478))
rm(FN_S1256, FN_S3478)
raw$percent_mito <- PercentageFeatureSet(raw, pattern = "MT-")
raw@meta.data$sample <- factor(raw@meta.data$BulkSample, levels = c("S1-PCW7","S2-PCW8","S3-PCW10","S5-PCW10","S4-PCW10.5","S6-PCW12", "S7-PCW12","S8-PCW12"))


```


```{r fig.width=6.5, fig.height=5.5}

p1 <- cellvio(raw, group.by = "BulkSample", features = c("nFeature_RNA", "nCount_RNA","percent_mito"), stack = T, 
            pt.size = 0.1, assay = "RNA", slot = "counts", cols = custom_colors$sample, font.size = 10, ttl.pos = "left")

p2 <- cellvio(obj, group.by = "sample", features = c("nFeature_RNA", "nCount_RNA","percent_mito"), stack = T,font.size = 10,
            pt.size = 0.1, assay = "RNA", slot = "counts", ylab.global = "Filtered counts", cols = custom_colors$sample, ttl.pos = "left")

p1 + p2
savefig(fig = p1 + p2, filename = file.path(dir.results, "figS2b"), width = 6.5, height = 5.5)

 
```


# FigS2c

```{r}

decontX <- readRDS("~/projects/singlecell/000-hudeca-nose/output/002-annotation/data/decontX.rds")

df <- data.frame(
  UMAP1 = integrated[["umap"]]@cell.embeddings[,1],
  UMAP2 = integrated[["umap"]]@cell.embeddings[,2],
  contamination = decontX$sce$decontX_contamination
)

font.size <- 10
reduction <- "umap"
dims <- c(1, 2)

# Main UMAP plot
plt <- ggplot(df, aes(UMAP1, UMAP2, color = contamination)) +
  geom_point(size = 0.3, alpha = 0.8) +
  scale_color_gradientn(
    colors = c("blue", "green", "yellow", "orange", "red"),
    guide = guide_colorbar(
      title = "Contamination",
      title.position = "left",
      title.theme = element_text(angle = 90, vjust = 0.5),
      barwidth = 0.7,
      barheight = 8,
      ticks = TRUE,
      frame.colour = "black",
      ticks.colour = "black"
    )
  ) +
  plot_theme(theme = "classic", font.size = font.size) +
  ggtitle("DecontX contamination") +
  theme(
    legend.position = "right",
    legend.title.align = 0.5
  ) +
  NoAxes()

# Axis labels
x.lab.reduc <- paste0("UMAP_", dims[1])
y.lab.reduc <- paste0("UMAP_", dims[2])

# Small axis inset
L <- 0.12
axis.df <- data.frame(
  x0 = c(0, 0),
  y0 = c(0, 0),
  x1 = c(L, 0),
  y1 = c(0, L)
)

axis.plot <- ggplot(axis.df) +
  geom_segment(
    aes(x = x0, y = y0, xend = x1, yend = y1),
    linewidth = 0.4,
    lineend = "round"
  ) +
  xlab(x.lab.reduc) +
  ylab(y.lab.reduc) +
  coord_fixed() +
  theme_classic(base_size = font.size) +
  theme(
    plot.background  = element_rect(fill = "transparent", colour = NA),
    panel.background = element_rect(fill = "transparent", colour = NA),
    axis.text        = element_blank(),
    axis.ticks       = element_blank(),
    axis.line        = element_blank(),
    panel.border     = element_blank(),
    plot.margin      = margin(0, 0, 0, 0)
  )

# Layout
figure.layout <- c(
  patchwork::area(t = 1,  l = 1,  b = 11, r = 11),  # main plot
  patchwork::area(t = 10, l = 1,  b = 11, r = 2)    # axis inset
)

final_plot <- plt + axis.plot +
  plot_layout(design = figure.layout)

final_plot
savefig(fig = final_plot, filename = file.path(dir.results, "figS2c"), width = 5, height = 4)
write.table(df, file.path(dir.results, "data/table_figS2c.tsv"), sep = "\t", row.names = T, quote = F)

```

# FigS2d

```{r fig.width=7, fig.height=5}

res <- plot_decontx_marker_percent(
  sce = decontX$sce, 
  #markers = c("XIST","UTY","KDM5D","HBB","HBA1"),
  markers = c("XIST","UTY","HBA1"),
  fontsize = 10, theme = "test",
  group_by = "ann2",ncol = 1, leg.pos = "bottom", leg.dir = "horizontal",
  assays = c("counts","decontXcounts"),
  plot_type = "bar", custom_colors = c("#151A1F", "#8CB9E6")
)

res$plot
savefig(fig = res$plot, filename = file.path(dir.results, "figS2d"), width = 7, height = 5)
write.table(res$table, file.path(dir.results, "data/table_figS2d.tsv"), sep = "\t", row.names = T, quote = F)
rm(decontX)

```





# FigS2e


```{r}
cellmap(integrated, group.by = "sample")
cellmap(obj, group.by = "sample")
```


```{r}

pre_int <- raw@meta.data %>%
  group_by(BulkSample) %>%
  summarise(n_cells = n()) %>%
  mutate(stage = "Pre-integration")
names(pre_int)[names(pre_int)=="BulkSample"]="sample"

post_int <- integrated@meta.data %>%
  group_by(sample) %>%
  summarise(n_cells = n()) %>%
  mutate(stage = "Post-integration")

post_sex_eryth <- obj@meta.data %>%
  group_by(sample) %>%
  summarise(n_cells = n()) %>%
  mutate(stage = "Post sex + erythroid")

# Combine
qc_counts <- bind_rows(pre_int, post_int, post_sex_eryth)


# Order samples by pre-QC counts
sample_order <- pre_int %>%
  arrange(desc(n_cells)) %>%
  pull(sample)

# Order stages
qc_counts$stage <- factor(qc_counts$stage, levels = c("Pre-integration", "Post-integration", "Post sex + erythroid"))

# Barplot
p <- ggplot(qc_counts, aes(x = sample, y = n_cells, fill = stage)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", linewidth = 0.2) +
  scale_fill_manual(values = c("Pre-integration" = "#19232E", "Post-integration" = "#5B7CA4", "Post sex + erythroid" = "#96ABC5")) +
  plot_theme(font.size = 10, theme = "classic", leg.pos = c(0.2,0.85), x.angle = 45) +
  labs(x = "", y = "Number of cells", fill = "QC stage") 
p
savefig(p, filename = file.path(dir.results, "figS2h") ,  width = 4.5, height = 3)

```

# Session Info

```{r session_info}
utils::capture.output(devtools::session_info())
```
