---
title: "HUDECA — Extended Data Figure 6"
author: "Mbouamboua Yvon <yvon.mbouamboua@inserm.fr>"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
date: '`r format(Sys.Date())`'
---

## Goal
Final figures

## Setup

```{r setup, include=TRUE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE, comment = "")
dir.main <- "/Users/yvon.mbouamboua/projects/singlecell/000-hudeca-nose"
dir.results <- file.path(dir.main, "output", "010-figures/extended-figure6")
dir.create(dir.results, showWarnings = FALSE, recursive = TRUE)
dir.create(file.path(dir.results, "data"), showWarnings = FALSE)

# Load packages
packages <- c("Seurat", "ggplot2", "dplyr", "grid", "decoupleR",
"SingleCellExperiment", "scran", "scater", "slingshot",
"pheatmap", "ComplexHeatmap", "ComplexUpset", "patchwork")
install_and_load <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
  library(pkg, character.only = TRUE)
}
invisible(lapply(packages, install_and_load))

# Load helper functions
utils_dir <- "~/projects/apps/"
r_files <- list.files(utils_dir, pattern = "\\.R$", full.names = TRUE)
invisible(lapply(r_files, source))

# Load custom colors 
custom_colors <-  readRDS(file.path(dir.main, "analysis/custom-colors-nature-safe.rds"))

```


# Load data

```{r}

obj <- readRDS(file.path(dir.main, "output/002-annotation/data/FN_harmony_clean.rds"))

```


# FigS6c

```{r fig.width=8, fig.height=5}

#colnames(obj@meta.data)[colnames(obj@meta.data) == "mito"] <- "percent_mito"

p <- cellvio(obj, features = c("CCNO", "FAT4", "RTN1"), group.by = "ann2",
  cols = custom_colors$ann2, ttl.pos = "left", font.size = 10,  stack = T, border.size = 0.1, pt.size = 0)

p
savefig(fig = p, filename = file.path(dir.results, "figS6c"), width = 8, height = 5)

```

