---
title: "HUDECA — Figure 2: Composition and development of the human olfactory system at PCW7-PCW12"
author: "Mbouamboua Yvon <yvon.mbouamboua@inserm.fr>"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
date: '`r format(Sys.Date())`'
---

## Goal
Final figures

## Setup

```{r setup, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
root <- '/Users/yvon.mbouamboua/projects/singlecell/000-hudeca'
outdir <- file.path(root, 'out', '000-github/fig2')
invisible(lapply(c(outdir, file.path(outdir, 'data'), file.path(outdir, 'plots')),
                 dir.create, recursive = TRUE, showWarnings = FALSE))
srcr <- file.path(root, 'src', 'R')
invisible(lapply(list.files(srcr, full.names = TRUE), source))
appdir <- Sys.getenv('APPS', '~/projects/apps')
if (dir.exists(appdir)) {
  pkgfile <- file.path(appdir, 'packages.R')
  if (file.exists(pkgfile)) sys.source(pkgfile, envir = .GlobalEnv)
  helper_files <- list.files(appdir, pattern = '\\.R$', full.names = TRUE)
  helper_files <- helper_files[basename(helper_files) != 'packages.R']
  invisible(lapply(helper_files, sys.source, envir = .GlobalEnv))
}

```


# Load data

```{r}

obj <- readRDS(file.path(root, "out/002-annotation/data/FN_harmony_clean.rds"))
custom_colors <-  readRDS(file.path(root, "analysis/custom-colors-nature-safe.rds"))

```


# Fig2b

```{r fig.width=5, fig.height=3.5}

sub <- cellslice(obj, group.by = "ann2", use.harmony = T, harmony.group = "sample", preprocess = T,
                     min.dist = 1, spread = 0.5, idents = c("OHBC", "CycBasal", "MV","SUS","GBC","INP","iOSN"))

p <- cellmap(sub, group.by = "ann2", label = F, legend = T, leg.ttl = "", figplot = T,  font.size = 10, pt.size = 0.5, n.cells = F)
p
savefig(fig = p, filename = file.path(outdir, "plots/gig2b"), width = 5.5, height = 3.5)

```


```{r fig.width=3, fig.height=3}

sub <- cellslice(obj,  group.by = "ann2", idents = c("RHBC","OHBC","GBC"), preprocess = F)

p <- celldot(sub, features = rev(c("TP63","KRT5","KRT17","CXCL14","SOX2","MEG3","COL17A1","RASSF6","MYBL1","NNAT","HES6","EZH2")), group.by = "ann2", 
             flip = T, font.size = 10, x.angle = 45, theme = "classic")
p
savefig(fig = p, filename = file.path(outdir, "plots/fig2c"), width = 3, height = 3)

```

# Fig2d

```{r fig.width=2, fig.height=4}

sub <- cellslice(obj, idents = c("OHBC","RHBC"), group.by = "ann2", preprocess = F)

p <- cellvio(sub, group.by = "ann2", features = c("MEG3"), pt.size = 0, font.size = 10, cols = custom_colors$ann2, show.pval = T, add.stats = T, pairwise = T)
p
savefig(fig = p, filename = file.path(outdir, "plots/fig2d"), width = 1.5, height = 4)

```



## Fig2e


```{r fig.width=8, fig.height=3}

sub <- cellslice(obj, group.by = "ann2", use.harmony = T, harmony.group = "sample",
                     min.dist = 1, spread = 0.5, idents = c("OHBC", "CycBasal", "MV","SUS","GBC","INP","iOSN"))

p <- cellpbulk(input = sub, donor.col = "sample", stage.col = "group",  cell.col  = "ann2", ncol = 7, show.p = F,
                  plot.type = "bar",  font.size = 10, facet.ttl.size = 14,axis.ttl.size = 10,axis.txt.size = 10,
                  x.angle = 45,facet.bg = FALSE,theme = "classic",mode = "light",leg.pos = "none", facet.title.size = 12,
                  stage.cols = custom_colors$group,donor.cols = custom_colors$sample, pt.size = 1.5, facet.by = "cell")

p$plot
savefig(fig = p$plot, filename = file.path(outdir, "plots/fig2e"), width = 8, height = 3)
write.table(p$source_data, file.path(outdir, "data/data_fig2c.tsv"), sep = "\t", row.names = F, quote = F)

```


# Session Info

```{r session_info}
utils::capture.output(devtools::session_info())
```


